name: CI of KinovaRobotModule

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    # Run on Sunday, Tuesday and Thursday nights
    - cron: '0 23 * * 0,1,4'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        build-type: [RelWithDebInfo]
        compiler: [gcc]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install mc_rtc
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install mc_rtc
        run: |
          set -e
          set -x
          curl -1sLf 'https://dl.cloudsmith.io/public/mc-rtc/head/setup.deb.sh' | sudo -E bash
          sudo apt install -y -qq libmc-rtc-dev ros-${ROS_DISTRO}-mc-rtc-plugin
      - name: Build and test
        uses: jrl-umi3218/github-actions/build-cmake-project@master
        with:
          compiler: ${{ matrix.compiler }}
          build-type: ${{ matrix.build-type }}
